modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="cbccompletesteelarmor"
version="${mod_version}"
displayName="CBC Complete steel Armor"
authors="Forsize"
description='''
CBC Complete steel Armor blocks for Create Big Cannons.
'''

[[dependencies.cbccompletesteelarmor]]
modId="neoforge"
type="required"
versionRange="[21.1.248,)"
ordering="NONE"
side="BOTH"

[[dependencies.cbccompletesteelarmor]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.cbccompletesteelarmor]]
modId="create"
type="required"
versionRange="[6.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cbccompletesteelarmor]]
modId="createbigcannons"
type="required"
versionRange="[5.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cbccompletesteelarmor]]
modId="sable"
type="required"
versionRange="[2.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cbccompletesteelarmor]]
modId="aeronautics_bundled"
type="required"
versionRange="[1.3.0,)"
ordering="AFTER"
side="BOTH"